name: Update routing.json

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download routing.json from SharePoint
        run: |
          curl -L "https://janneyelectric.sharepoint.com/:u:/s/JanneyElectric/IQAVIVqqElDPTISsboDRWG-RAcXayHSjqukwrsJIXws9DAY?e=o5h5fm&download=1" -o routing.json

          if grep -q "403 FORBIDDEN" routing.json; then
            echo "Downloaded 403 page instead of JSON"
            exit 1
          fi

          if ! grep -q '"Unit_ID"' routing.json; then
            echo "Did not download valid routing JSON"
            exit 1
          fi

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add routing.json
          git diff --cached --quiet || git commit -m "Update routing.json"
          git push
